// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

interface ILlamaGuardOracle {
    // Events
    event UpdateReceived(uint256 supply, uint256 price, uint256 state);

    // Read-only getters (generated by public state variables)
    function proxyAddress() external view returns (address);
    function supply() external view returns (uint256);
    function state() external view returns (uint256);

    // Mutators
    function setProxyAddress(address _proxyAddress) external;
    function updateData(uint256 _supply, uint256 _price, uint256 _state) external;

    // Views
    function getData() external view returns (uint256, uint256, int256, uint256);
}
