// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

interface ILlamaGuardOracle {
    // Events
    event UpdateReceived(uint256 supply, uint256 price, uint256 state);

    // Read-only getters (generated by public state variables)
    function supply() external view returns (uint256);
    function state() external view returns (uint256);

    // Mutators
    function updateData(bytes calldata data) external;

    // Views
    function getData() external view returns (uint256, uint256, int256, uint256);
}
